const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

// Define the path to your .env.local file for local development
const envPath = path.resolve(__dirname, '../.env.local');

// Load .env.local if it exists
if (fs.existsSync(envPath)) {
  dotenv.config({ path: envPath });
}

// This is where your final config file will be created
const configPath = path.resolve(__dirname, '../client/src/config.js');

// This creates the content of the config file.
// It now correctly reads the NEXT_PUBLIC_ prefixed variables for deployment,
// and falls back to the VITE_ prefixed variables for local development.
const config = `
// This file is automatically generated by scripts/create-config.js. Do not edit.
export const firebaseConfig = {
  apiKey: "${process.env.NEXT_PUBLIC_VITE_FIREBASE_API_KEY || process.env.VITE_FIREBASE_API_KEY}",
  authDomain: "${process.env.NEXT_PUBLIC_VITE_FIREBASE_AUTH_DOMAIN || process.env.VITE_FIREBASE_AUTH_DOMAIN}",
  projectId: "${process.env.NEXT_PUBLIC_VITE_FIREBASE_PROJECT_ID || process.env.VITE_FIREBASE_PROJECT_ID}",
  storageBucket: "${process.env.NEXT_PUBLIC_VITE_FIREBASE_STORAGE_BUCKET || process.env.VITE_FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${process.env.NEXT_PUBLIC_VITE_FIREBASE_MESSAGING_SENDER_ID || process.env.VITE_FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${process.env.NEXT_PUBLIC_VITE_FIREBASE_APP_ID || process.env.VITE_FIREBASE_APP_ID}",
};

export const aiConfig = {
  apiKey: "${process.env.NEXT_PUBLIC_VITE_GOOGLE_GENERATIVE_LANGUAGE_API_KEY || process.env.VITE_GOOGLE_GENERATIVE_LANGUAGE_API_KEY}",
};

export const weatherConfig = {
  apiKey: "${process.env.NEXT_PUBLIC_VITE_WEATHER_API_KEY || process.env.VITE_WEATHER_API_KEY}",
};
`;

// This writes the file to your client's src directory
fs.writeFileSync(configPath, config);
console.log('Successfully created config file at client/src/config.js');